#!/bin/bash
# Copyright 2013, Maxwell Rees, sthrs.me
# Licensed under the Eiffel Forum License 2.

function admin() {
   case "$1" in
      quit)
         if [ -z "$args" ]; then
            args='Exeunt'
         fi
         log '* QUIT'
         send "QUIT :$args"
         sleep 2
         exit 0
         ;;
      join)
         log "* JOIN $args"
         send "JOIN $args"
         ;;
      part)
         log "* PART $args"
         send "PART $args"
         ;;
      nick)
         log "* NICK ${arg[0]}"
         mynick=${arg[0]}
         send "NICK ${arg[0]}"
         ;;
      say)
         log "* SAY $args"
         saying=${arg[@]:1}
         say "${arg[0]}" "$saying"
         ;;
      reload)
         log '* RELOAD'
         changes=$( (source data/configuration) 2>&1)
         if [ -z "$changes" ]; then
            changes='Reload complete.'
         fi
         say "$chan" "$changes"
         ;;
      sed)
         log "* SED '$args'"
         changes=$( (sed -i.bak "$args" data/brain.db) 2>&1)
         if [ -z "$changes" ]; then
            changes=$(diff -U 0 data/brain.db.bak data/brain.db | grep ^@ | wc -l)
         fi
         say "$chan" "$changes line(s) were modified."
         ;;
      let)
         log "* LET '$args'"
         changes=$( (let "$args") 2>&1)
         if [ -z "$changes" ]; then
            let "$args"
            changes='Okay.'
         fi
         say "$chan" "$changes"
         ;;
   esac
}
