#!/bin/bash

function basic() {
   case "$1" in
         up|uptime)
            now=$(date +%s)
            delta=$(($(($now-$startup))/60))
            say "$chan" "About $delta minutes"
            unset now delta
            ;;
         help)
            say "$chan" 'See https://wiki.interlinked.me/page/Stan'
            ;;
         sleep)
            say "$chan" 'Okay.'
            shutupline=$(date +%s)
            ;;
         wake)
            say "$chan" 'HELLO'
            shutupline=0
            ;;
         dc)
            args=$(echo -E "$args" | sed 's/[\!?][^<>=]//g')
            out=$(echo -E "$args" | dc | head -c 400 | sed ':a;N;$!ba;s/\n/<nl>/g')
            say "$chan" "$out"
            ;;
         police)
            case "$args" in
               ON)
                  police='ON'
                  say "$chan" 'POLICE:ON'
                  ;;
               OFF)
                  police='OFF'
                  say "$chan" 'POLICE:OFF'
                  ;;
               ON_FULLPOWER)
                  police='ON_FULLPOWER'
                  say "$chan" 'POLICE:ON_FULLPOWER'
                  ;;
               *)
                  say "$chan" 'POLICE:'"$police"
                  ;;
            esac
            ;;
   esac
}
