#!/bin/bash
# Copyright 2013, Maxwell Rees, sthrs.me
# Licensed under the Eiffel Forum License 2.

function basic() {
   case "$1" in
      up|uptime)
         now=$(date +%s)
         delta=$(($(($now-$startup))/60))
         say "$chan" "About $delta minutes"
         unset now delta
         ;;
      help)
         say "$chan" 'See https://wiki.interlinked.me/page/Stan'
         ;;
      shutup|sleep)
         say "$chan" 'Okay.'
         shutupline=$(date +%s)
         ;;
      wake)
         say "$chan" 'HELLO'
         shutupline=0
         ;;
      dc)
         args=$(echo -E "$args" | sed 's/[\!?][^<>=]//g')
         out=$(echo -E "$args" | dc | head -c 400 | sed ':a;N;$!ba;s/\n/<nl>/g')
         say "$chan" "$out"
         ;;
      ping)
         out=$(ping -qc 4 "$args" 2>&1 | grep -i '\(^PING\)\|packets' | tr '\n' ' ')
         say "$chan" "$out"
         ;;
      host)
         out=$(host "$args" | grep -oE "address \S+" | sed 's/address //g' | tr '\n' ' ')
         say "$chan" "$out"
         ;;
      v|version)
         out=$(git rev-parse HEAD)
         say "$chan" "Version: commit $out"
         ;;
      w|wik)
         out=$(dig @resolver1.opendns.com +short txt "$args".wp.dg.cx)
         say "$chan" "$out"
         ;;
   esac
}
